# Generated by Django 3.1.7 on 2021-03-10 15:21

from django.db import migrations, models
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', faicon.fields.FAIconField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Подзаголовок')),
            ],
        ),
        migrations.AddField(
            model_name='titleblock',
            name='button',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='titleblock',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
