# Generated by Django 3.1.7 on 2021-03-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0002_auto_20210310_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iconblock',
            options={'ordering': ['order'], 'verbose_name': 'Иконка', 'verbose_name_plural': 'Блок иконок'},
        ),
        migrations.AddField(
            model_name='iconblock',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок расположения'),
        ),
        migrations.AlterField(
            model_name='iconblock',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
