# Generated by Django 3.1.7 on 2021-03-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0005_auto_20210310_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='social',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socials', to='siteblocks.contact', verbose_name='Контакты'),
        ),
    ]
