# Generated by Django 3.1.7 on 2021-03-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0006_auto_20210311_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='buy_button',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Кнопка Купить'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='info_button',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Кнопка Подробнее'),
        ),
    ]
