# Generated by Django 3.1.7 on 2021-04-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0012_auto_20210330_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='siteblocks.gallery'),
        ),
    ]
