# Generated by Django 3.1.7 on 2021-04-22 10:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0013_auto_20210402_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Блок доп товар',
                'verbose_name_plural': 'Блок доп товары',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='iconblock',
            name='icon',
            field=models.FileField(max_length=255, upload_to='', verbose_name='Изображение'),
        ),
    ]
