# Generated by Django 3.1.7 on 2021-04-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0014_auto_20210422_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryblock',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
