# Generated by Django 3.1.7 on 2021-04-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0016_iconblock_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='code',
            field=models.CharField(default='acc-', max_length=60, verbose_name='Артикул'),
        ),
    ]
