# Generated by Django 3.1.7 on 2021-04-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0017_accessory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='code',
            field=models.CharField(default='acc-', max_length=60, unique=True, verbose_name='Артикул'),
        ),
    ]
