# Generated by Django 3.1.7 on 2021-03-05 11:27

import accessories.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название товара')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название категории')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('image', models.ImageField(max_length=255, upload_to=accessories.models.category_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=accessories.models.category_directory_path)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.accessory', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.category', verbose_name='Категория'),
        ),
    ]
