# Generated by Django 3.1.7 on 2021-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='code',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
