# Generated by Django 3.1.7 on 2021-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0003_auto_20210428_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='code',
            field=models.CharField(max_length=60, verbose_name='Артикул'),
        ),
    ]
