# Generated by Django 3.1.7 on 2021-03-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquetsetsize',
            name='bouquet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flowersets.bouquetset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bouquetsetsize',
            name='name',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Middle'), ('L', 'Large')], default='S', max_length=50, verbose_name='Название'),
        ),
    ]
