# Generated by Django 3.1.7 on 2021-03-09 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0002_auto_20210307_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_description', models.TextField()),
                ('recomedation', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='bouquetset',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='number',
        ),
        migrations.RemoveField(
            model_name='bouquetsetsize',
            name='bouquet',
        ),
        migrations.RemoveField(
            model_name='bouquetsetsize',
            name='name',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bouquet',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bouquetimage',
            name='bouquet_size',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L')], default=1, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='bouquetsetsize',
            name='set_heigth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bouquetsetsize',
            name='set_size',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L')], default=1, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='bouquetimage',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flowersets.bouquet', verbose_name='Букет'),
        ),
        migrations.DeleteModel(
            name='BouquetSet',
        ),
    ]
