# Generated by Django 3.1.7 on 2021-03-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0003_auto_20210309_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquetsetsize',
            name='set_size',
        ),
    ]
