# Generated by Django 3.1.7 on 2021-03-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0006_auto_20210309_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'ordering': ['release_date']},
        ),
        migrations.AlterModelOptions(
            name='bouquetsetsize',
            options={'ordering': ['id']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bouquetimage',
            order_with_respect_to='bouquet',
        ),
    ]
