# Generated by Django 3.1.7 on 2021-03-09 22:36

from django.db import migrations, models
import flowersets.models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0008_auto_20210309_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='release_date',
            field=models.DateField(verbose_name='В прдаже с'),
        ),
        migrations.AlterField(
            model_name='bouquetimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to=flowersets.models.image_directory_path, verbose_name='Фото'),
        ),
    ]
