# Generated by Django 3.1.7 on 2021-03-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0010_auto_20210330_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'ordering': ['on_showcase'], 'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='release_date',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='on_showcase',
            field=models.BooleanField(default=False),
        ),
    ]
