# Generated by Django 3.1.7 on 2021-03-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0012_auto_20210330_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquetsetsize',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
