# Generated by Django 3.1.7 on 2021-06-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0018_auto_20210428_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнение к наименованию')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='bouquetsetsize',
            options={'ordering': ['-set_size', 'id'], 'verbose_name': 'Сет', 'verbose_name_plural': 'Сеты'},
        ),
        migrations.AddField(
            model_name='bouquetimage',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flowersets.bouquetsetsize', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='bouquetimage',
            name='bouquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flowersets.bouquet', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='bouquetimage',
            name='bouquet_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='S', max_length=1, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='bouquetsetsize',
            name='set_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='S', max_length=1, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='bouquetsetsize',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='flowersets.subscription', verbose_name='Букет'),
        ),
    ]
