# Generated by Django 3.1.7 on 2021-06-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0019_auto_20210621_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquetimage',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flowersets.bouquetsetsize', verbose_name='Сет'),
        ),
        migrations.AlterUniqueTogether(
            name='bouquetimage',
            unique_together=set(),
        ),
        migrations.AlterOrderWithRespectTo(
            name='bouquetimage',
            order_with_respect_to='set',
        ),
        migrations.RemoveField(
            model_name='bouquetimage',
            name='bouquet',
        ),
        migrations.RemoveField(
            model_name='bouquetimage',
            name='bouquet_size',
        ),
        migrations.DeleteModel(
            name='Bouquet',
        ),
    ]
