# Generated by Django 3.1.7 on 2021-06-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0020_auto_20210621_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquetsetsize',
            name='set',
        ),
        migrations.AddField(
            model_name='bouquetsetsize',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='flowersets.subscription', verbose_name='Подписка'),
        ),
    ]
