# Generated by Django 3.1.7 on 2021-06-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0021_auto_20210621_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquetsetsize',
            name='short_title',
        ),
    ]
