# Generated by Django 3.1.7 on 2021-06-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0022_remove_bouquetsetsize_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
    ]
