# Generated by Django 3.1.7 on 2021-06-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0023_auto_20210621_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='На витрине'),
        ),
    ]
