# Generated by Django 3.1.7 on 2021-06-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0025_testboquet'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='button',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке'),
        ),
    ]
