# Generated by Django 3.1.7 on 2021-03-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('first_delivery', models.DateField(blank=True, null=True, verbose_name='Дата первой доставки')),
                ('delivery_start_time', models.TimeField(default='10:00:00', verbose_name='Доставить с')),
                ('delivery_end_time', models.TimeField(default='21:00:00', verbose_name='Доставить до')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Сумма')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=60, verbose_name='Телефон')),
                ('name2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Получатель')),
                ('phone2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Телефон получателя')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('building', models.CharField(max_length=10, verbose_name='Дом')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('intercom', models.CharField(blank=True, max_length=10, null=True, verbose_name='Домофон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен?')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-id'],
            },
        ),
    ]
