# Generated by Django 3.1.7 on 2021-04-14 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210402_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=60, verbose_name='Промокод')),
                ('expiration', models.DateField(default=datetime.date(2021, 4, 14))),
                ('discount', models.PositiveIntegerField(default=10)),
                ('accessories', models.BooleanField(default=False, verbose_name='Аксессуары')),
                ('s_set', models.BooleanField(default=True, verbose_name='Размер S')),
                ('m_set', models.BooleanField(default=True, verbose_name='Размер M')),
                ('l_set', models.BooleanField(default=False, verbose_name='Размер L')),
            ],
        ),
    ]
