# Generated by Django 3.1.7 on 2021-04-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_promo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['-id'], 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
