# Generated by Django 3.1.7 on 2021-04-15 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210415_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='expiration',
            field=models.DateField(default=datetime.date(2021, 4, 16)),
        ),
    ]
