# Generated by Django 3.1.7 on 2021-04-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210420_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='orders.order'),
        ),
    ]
