# Generated by Django 3.1.7 on 2021-04-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210421_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Сумма'),
        ),
    ]
