# Generated by Django 3.1.7 on 2021-04-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210421_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sber',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
