# Generated by Django 3.1.7 on 2021-04-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_sber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
