# Generated by Django 3.1.7 on 2021-04-28 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210427_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='code',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='code',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expiration',
            field=models.DateField(default=datetime.date(2021, 4, 28)),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 4, 28)),
        ),
    ]
