# Generated by Django 3.1.7 on 2021-04-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210428_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sber',
        ),
    ]
