# Generated by Django 3.1.7 on 2021-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_order_sber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер Сбер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус'),
        ),
    ]
