# Generated by Django 3.1.7 on 2021-05-01 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20210428_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Чек'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expiration',
            field=models.DateField(default=datetime.date(2021, 5, 1)),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 5, 1)),
        ),
    ]
