# Generated by Django 3.1.7 on 2021-05-02 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checksum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expiration',
            field=models.DateField(default=datetime.date(2021, 5, 2)),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 5, 2)),
        ),
    ]
