# Generated by Django 3.1.7 on 2021-05-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20210502_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsRefunded',
        ),
    ]
