# Generated by Django 3.1.7 on 2021-05-03 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_delete_goodsrefunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='goods',
            name='refunded',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возвращено'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expiration',
            field=models.DateField(default=datetime.date(2021, 5, 3)),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 5, 3)),
        ),
    ]
