# Generated by Django 3.1.7 on 2021-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20210503_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='refunded',
            field=models.PositiveIntegerField(default=0, verbose_name='Возвращено'),
        ),
    ]
