# Generated by Django 3.1.7 on 2021-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20210503_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='refunded',
            field=models.FloatField(default=0, verbose_name='Возвращено'),
        ),
    ]
