# Generated by Django 3.1.7 on 2021-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20210503_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
    ]
