# Generated by Django 3.1.7 on 2021-06-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20210621_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='m_set',
            field=models.BooleanField(default=False, verbose_name='Размер M'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='s_set',
            field=models.BooleanField(default=False, verbose_name='Размер S'),
        ),
    ]
