# Generated by Django 3.1.7 on 2021-06-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20210621_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='accessories',
            new_name='accessory',
        ),
    ]
