# Generated by Django 3.1.7 on 2021-06-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20210622_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='accessories',
            field=models.BooleanField(default=False, verbose_name='Аксессуары'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='promo',
            name='m_set',
            field=models.BooleanField(default=True, verbose_name='Размер M'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='s_set',
            field=models.BooleanField(default=True, verbose_name='Размер S'),
        ),
    ]
