# Generated by Django 3.1.7 on 2021-06-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20210622_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='m_set',
            field=models.BooleanField(default=False, verbose_name='Размер M'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='s_set',
            field=models.BooleanField(default=False, verbose_name='Размер S'),
        ),
    ]
