# Generated by Django 3.1.7 on 2021-06-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20210622_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='present',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Презент'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
