# Generated by Django 3.1.7 on 2021-06-29 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0026_subscription_button'),
        ('orders', '0041_auto_20210622_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='l_set',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='m_set',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='s_set',
        ),
        migrations.AddField(
            model_name='promo',
            name='subsribtions',
            field=models.ManyToManyField(related_name='promos', to='flowersets.Subscription', verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expiration',
            field=models.DateField(default=datetime.date(2021, 6, 29)),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 6, 29)),
        ),
    ]
