# Generated by Django 3.1.7 on 2021-06-29 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersets', '0026_subscription_button'),
        ('orders', '0042_auto_20210629_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='subsribtions',
        ),
        migrations.AddField(
            model_name='promo',
            name='sets',
            field=models.ManyToManyField(related_name='promos', to='flowersets.BouquetSetSize', verbose_name='Сеты'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expiration',
            field=models.DateField(default=datetime.date(2021, 6, 29), verbose_name='Дествителен до'),
        ),
    ]
