# Generated by Django 3.1.7 on 2021-07-15 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20210629_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialorder',
            name='delivery_option',
            field=models.BooleanField(default=False, verbose_name='Показывать время доставки?'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expiration',
            field=models.DateField(default=datetime.date(2021, 7, 15), verbose_name='Дествителен до'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 7, 15)),
        ),
    ]
