# Generated by Django 3.1.7 on 2021-07-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_auto_20210715_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialorder',
            name='goods',
            field=models.CharField(default='Индивидуальная подписка на месяц', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
