# Generated by Django 3.1.7 on 2021-07-17 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_auto_20210715_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emailed',
            field=models.BooleanField(default=False, verbose_name='Письмо'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expiration',
            field=models.DateField(default=datetime.date(2021, 7, 17), verbose_name='Дествителен до'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 7, 17)),
        ),
    ]
